FROM python:3.11-slim

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install flask requests

COPY app.py .
COPY index.html .

RUN mkdir -p audios
RUN echo "[]" > records.json

EXPOSE 5000

CMD ["python", "app.py"]